import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
const files={};for(const name of ['app','core','cloud','exams','product'])files[name]=await readFile(new URL(`../dist/${name}.js`,import.meta.url),'utf8');
const dataModule=source=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const product=dataModule(files.product),core=dataModule(files.core),cloud=dataModule(files.cloud),exams=dataModule(files.exams.replace("'./product.js'",JSON.stringify(product)));
const sample={id:'PUBLIC-Q1',version:1,status:'ready',stem:'測試題幹',options:['甲','乙','丙','丁','戊'],answer:0,part:1,examTracks:['eaqe','sqe'],free:true,concept:'合成測試概念',explanation:'訪客測試解說',optionNotes:['一','二','三','四','五']};
const response=(status,data)=>({status,ok:status>=200&&status<300,json:async()=>data});
const memory=()=>{const map=new Map();return {getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key),map};};
async function load({signed=false,offline=false,hash='#practice',structuredExplanation=false,blockedQuestionIds=[],reviewUnavailable=false,cloudReviews=false,conceptStatus=200,conceptPages=null,resetSessionsRevoked=true}={}){
 const saved=new Map();const set=(key,value)=>{saved.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{value,writable:true,configurable:true});};
 const events={},windowEvents={},main={innerHTML:'',focus(){}},notice={textContent:''},dialog={innerHTML:'',open:false,showModal(){this.open=true;},close(){this.open=false;},addEventListener(){},querySelector(){return {onclick:null};}},accountLink={href:'#login',textContent:'登入'};
 const doc={hidden:false,title:'',querySelector:selector=>selector==='main'?main:selector==='dialog'?dialog:selector==='#notice'?notice:selector==='.account-link'?accountLink:selector==='.skip'?{addEventListener(){}}:{focus(){},textContent:'',value:'',checkValidity:()=>true},querySelectorAll:()=>[],addEventListener:(type,fn)=>events[type]=fn,getElementById:()=>null,createElement:()=>({click(){}})};
 const account={user:{id:'10000000-0000-4000-8000-000000000001',email:'learner@example.test',verified:true},settings:{track:'eaqe',examDate:''},settingsVersion:1,entitlement:{plan:'free',expiresAt:null},catalog:[]};
 const session={id:'20000000-0000-4000-8000-000000000001',version:1,index:0,status:'active',mode:'practice',track:'eaqe',items:[{id:sample.id,version:1,stem:'伺服器題幹',options:[{id:'server-option-b',text:'乙'},{id:'server-option-a',text:'甲'}],part:1,tracks:['eaqe'],isFree:true}]};
 const calls=[];let networkOffline=offline,loggedIn=signed,serverAttempt=null,reviewCompleted=false,currentConceptStatus=conceptStatus;
 const fetcher=async(path,options={})=>{calls.push({path,options});if(path==='./questions.json')return response(200,[sample]);if(path==='./content-review.json')return response(reviewUnavailable?503:200,{reviewDate:'2026-10-04',blockedQuestionIds,commercialApprovedCount:0});if(path==='/api/config')return response(200,{authEnabled:true,authConfigured:true,termsVersion:'test-only',privacyVersion:'test-only',passwordMinLength:12});if(networkOffline&&path.startsWith('/api/')&&!path.startsWith('/api/auth/'))throw Error('offline');
  if(path==='/api/account')return loggedIn?response(200,account):response(401,{error:{code:'unauthenticated',message:'請登入。'}});
  if(path==='/api/auth/refresh')return response(401,{error:{code:'unauthenticated',message:'請登入。'}});
  if(path.startsWith('/api/sync?'))return response(200,{events:cloudReviews?[{kind:'attempt',payload:{attempt:{id:'30000000-0000-4000-8000-000000000001',questionId:sample.id,questionVersion:1,part:1,concept:'跨裝置弱項概念',correct:false,uncertain:false,at:'2026-10-04T10:00:00+08:00',mode:'practice'},review:{status:reviewCompleted?'completed':'wrong',due:'2026-10-05',successes:reviewCompleted?2:0}}}]:[],cursor:'0',hasMore:false,settings:account.settings,settingsVersion:1,dailyUsage:{}});
  if(path.startsWith('/api/review-concepts?')){if(currentConceptStatus!==200)return response(currentConceptStatus,{error:{code:'concept_unavailable',message:'概念服務暫時未能使用。'}});const params=new URLSearchParams(path.split('?')[1]);if(conceptPages)return response(200,conceptPages[params.get('after')]||{items:[],cursor:params.get('after')||'',hasMore:false});return response(200,{items:cloudReviews&&!reviewCompleted?[{questionId:sample.id,questionVersion:1,part:1,concept:'跨裝置弱項概念',core:'新裝置的核心概念',apply:'新裝置的逐步套用',memory:'新裝置的易錯提示'}]:[],cursor:sample.id,hasMore:false});}
  if(path==='/api/auth/reset'){loggedIn=false;return response(200,{message:'密碼已更新。',sessionsRevoked:resetSessionsRevoked});}
  if(path==='/api/practice-sessions'&&options.method==='POST')return response(200,{session,cursor:'1'});
  if(path==='/api/attempts'){const body=JSON.parse(options.body);serverAttempt={id:body.eventId,sessionId:session.id,questionId:sample.id,questionVersion:1,part:1,concept:'伺服器核實概念',optionId:body.optionId,correct:false,uncertain:body.uncertain,at:'2026-10-04T10:00:00+08:00',day:'2026-10-04',seconds:0,mode:'practice'};return response(200,{attempt:serverAttempt,review:{status:'wrong',due:'2026-10-05',successes:0},explanation:{answerOptionId:'server-option-a',content:structuredExplanation?{core:'核心概念正文',apply:'情境逐步套用',options:{'server-option-a':'甲的正確理由','server-option-b':'乙的錯誤理由'},memory:'必要條件及易錯提示'}:'伺服器確認的解說'},sessionVersion:2,cursor:'2'});}
  if(path==='/api/auth/logout'){loggedIn=false;return response(200,{loggedOut:true});}
  return response(404,{error:{code:'not_found',message:'找不到。'}});
 };
 set('document',doc);set('window',{addEventListener:(type,fn)=>windowEvents[type]=fn,scrollTo(){},history:{replaceState(_s,_t,value){globalThis.location.hash=value.split('#')[1]?'#'+value.split('#')[1]:'';}}});let currentHash=hash;set('location',{get hash(){return currentHash;},set hash(value){currentHash=value.startsWith('#')?value:'#'+value;},pathname:'/',search:'',protocol:'http:'});set('navigator',{});set('localStorage',memory());set('sessionStorage',memory());set('fetch',fetcher);set('setInterval',()=>0);set('setTimeout',()=>0);set('clearTimeout',()=>{});set('FormData',class{constructor(form){this.data=form.data;}get(key){return this.data[key]??null;}});
 const src=files.app.replace("'./exams.js'",JSON.stringify(exams)).replace("'./product.js'",JSON.stringify(product)).replace("'./core.js'",JSON.stringify(core)).replace("'./cloud.js'",JSON.stringify(cloud))+`\nexport const testHarness={start,quiz,history,analysis,render,performLogout,paidActive,outbox,getState:()=>state,getAccount:()=>account,mergeSession,syncCloud,concepts,loadReviewConcepts,freeCount,home,pricing,helpPage,setAccount,setGuest,getConceptCache:()=>conceptCache};\n// ${crypto.randomUUID()}`;
 const module=await import(dataModule(src));return {h:module.testHarness,events,windowEvents,main,notice,calls,account,session,setOffline:value=>networkOffline=value,setReviewCompleted:value=>reviewCompleted=value,setConceptStatus:value=>currentConceptStatus=value,cleanup(){for(const [key,descriptor]of saved)descriptor?Object.defineProperty(globalThis,key,descriptor):delete globalThis[key];}};
}
test('guest paid claims never unlock and existing private records are not uploaded',async()=>{
 const app=await load();try{localStorage.setItem('propexam-hk-v3',JSON.stringify({entitlement:{plan:'full',expiresAt:'2099-12-31'}}));assert.equal(app.h.paidActive(),false);assert.equal(app.h.getAccount(),null);assert.equal(app.calls.filter(c=>['/api/attempts','/api/review-events'].includes(c.path)).length,0);}finally{app.cleanup();}
});
test('signed answer uses shuffled stable option ID and only server-confirmed grading',async()=>{
 const app=await load({signed:true});try{await app.h.start([],'練習');assert.match(app.h.quiz(),/伺服器題幹/);assert.doesNotMatch(app.h.quiz(),/訪客測試解說/);const form={id:'answer-form',data:{answer:'0',uncertain:null}};await app.events.submit({target:form,preventDefault(){}});const sent=app.calls.find(c=>c.path==='/api/attempts');assert.equal(JSON.parse(sent.options.body).optionId,'server-option-b');assert.equal(JSON.parse(sent.options.body).correct,undefined);assert.equal(app.h.getState().attempts[0].correct,false);assert.match(app.h.quiz(),/答案錯誤/);assert.match(app.h.quiz(),/伺服器確認的解說/);assert.equal(app.h.outbox.pending,0);}finally{app.cleanup();}
});
test('offline answer preserves pending event without revealing correctness; recovery resends once',async()=>{
 const app=await load({signed:true});try{await app.h.start([],'練習');app.setOffline(true);await app.events.submit({target:{id:'answer-form',data:{answer:'0',uncertain:'on'}},preventDefault(){}});assert.equal(app.h.getState().attempts.length,0);assert.equal(app.h.outbox.pending,1);assert.doesNotMatch(app.h.quiz(),/答案正確|答案錯誤|伺服器確認的解說/);const eventId=app.h.outbox.events[0].id;app.setOffline(false);await app.h.syncCloud({manual:true});assert.equal(app.h.outbox.pending,0);assert.equal(app.h.getState().attempts.length,1);const ids=app.calls.filter(c=>c.path==='/api/attempts').map(c=>JSON.parse(c.options.body).eventId);assert.deepEqual(ids,[eventId,eventId]);}finally{app.cleanup();}
});
test('logout clears active account state while retaining only its unsynced outbox',async()=>{
 const app=await load({signed:true});try{await app.h.start([],'練習');app.setOffline(true);await app.events.submit({target:{id:'answer-form',data:{answer:'0'}},preventDefault(){}});const key=app.h.outbox.key;assert.ok(localStorage.getItem(key));app.setOffline(false);await app.h.performLogout();assert.equal(app.h.getAccount(),null);assert.equal(app.h.getState().attempts.length,0);assert.equal(app.h.getState().session,null);assert.ok(localStorage.getItem(key));assert.equal(localStorage.getItem(`propexam-cloud-v1:${app.account.user.id}:draft`),null);}finally{app.cleanup();}
});
test('email callback token is removed from URL before any startup request and is never stored',async()=>{
 const app=await load({hash:'#auth-callback?token_hash=synthetic-secret&type=signup'});try{assert.equal(location.hash,'#login');const callback=app.calls.find(c=>c.path==='/api/auth/callback');assert.ok(callback);assert.deepEqual(JSON.parse(callback.options.body),{tokenHash:'synthetic-secret',type:'signup'});assert.equal(app.h.getAccount(),null);assert.doesNotMatch(Array.from(localStorage.map.values()).join(' '),/synthetic-secret/);assert.doesNotMatch(app.main.innerHTML,/synthetic-secret/);}finally{app.cleanup();}
});
test('database explanation fields render completely and option notes follow stable shuffled IDs',async()=>{
 const app=await load({signed:true,structuredExplanation:true});try{await app.h.start([],'練習');await app.events.submit({target:{id:'answer-form',data:{answer:'0'}},preventDefault(){}});const html=app.h.quiz();for(const text of ['核心概念正文','情境逐步套用','必要條件及易錯提示','伺服器核實概念'])assert.match(html,new RegExp(text));assert.match(html,/<strong>A<\/strong> · 乙的錯誤理由/);assert.match(html,/<strong>B<\/strong> · 甲的正確理由/);assert.doesNotMatch(html,/解說尚未取得/);}finally{app.cleanup();}
});
test('quarantined questions and missing review metadata cannot start guest practice',async()=>{
 for(const options of [{blockedQuestionIds:[sample.id]},{reviewUnavailable:true}]){const app=await load(options);try{await app.h.start([sample],'試用');assert.equal(app.h.getState().session,null);assert.match(app.main.innerHTML,/題庫尚未準備完成|覆核清單未能載入/);assert.equal(app.calls.filter(c=>c.path==='/api/attempts').length,0);}finally{app.cleanup();}}
});

test('free availability uses actual filtered guest questions and current server catalog',async()=>{
 const guest=await load({hash:'#home'});try{assert.equal(guest.h.freeCount(),1);assert.match(guest.h.home(),/1 題免費試做/);assert.match(guest.h.pricing(),/目前可免費試做 1 題/);assert.doesNotMatch(guest.h.pricing(),/20 題/);}finally{guest.cleanup();}
 const blocked=await load({blockedQuestionIds:[sample.id]});try{assert.equal(blocked.h.freeCount(),0);assert.match(blocked.h.pricing(),/0 題免費試做/);}finally{blocked.cleanup();}
 const signed=await load({signed:true});try{assert.equal(signed.h.freeCount(),0);signed.account.catalog=[{track:'eaqe',part:1,free:3,total:7,available:3},{track:'sqe',part:1,free:5,total:8,available:5}];assert.equal(signed.h.freeCount(),3);assert.match(signed.h.home(),/3 題免費試做/);}finally{signed.cleanup();}
});
test('new device reads cloud concepts without a loaded question session and removes completed weaknesses',async()=>{
 const app=await load({signed:true,cloudReviews:true,hash:'#concepts'});try{assert.equal(app.h.getState().session,null);for(const text of ['跨裝置弱項概念','新裝置的核心概念','新裝置的逐步套用','新裝置的易錯提示'])assert.match(app.h.concepts(),new RegExp(text));assert.doesNotMatch(app.h.concepts(),/尚未建立弱項/);const req=app.calls.find(call=>call.path.startsWith('/api/review-concepts?'));assert.equal(req.options.headers['X-App-Account'],app.account.user.id);assert.doesNotMatch(Array.from(localStorage.map.values()).join(' '),/新裝置的核心概念/);app.setReviewCompleted(true);await app.h.syncCloud();assert.match(app.h.concepts(),/尚未建立弱項/);assert.doesNotMatch(app.h.concepts(),/新裝置的核心概念/);}finally{app.cleanup();}
});
test('concept failures and inaccessible pending records never display false absence of weaknesses',async()=>{
 const app=await load({signed:true,cloudReviews:true,hash:'#concepts',conceptStatus:503});try{assert.match(app.h.concepts(),/概念未能載入|概念服務暫時未能使用/);assert.doesNotMatch(app.h.concepts(),/尚未建立弱項/);app.setConceptStatus(200);await app.h.loadReviewConcepts({force:true});assert.match(app.h.concepts(),/新裝置的核心概念/);app.setConceptStatus(503);await app.h.loadReviewConcepts({force:true});assert.doesNotMatch(app.h.concepts(),/新裝置的核心概念|尚未建立弱項/);}finally{app.cleanup();}
 const expired=await load({signed:true,cloudReviews:true,hash:'#concepts',conceptPages:{'':{items:[],cursor:'',hasMore:false}}});try{assert.match(expired.h.concepts(),/目前沒有可讀取的概念/);assert.match(expired.h.concepts(),/待重溫紀錄仍保留/);assert.doesNotMatch(expired.h.concepts(),/尚未建立弱項/);}finally{expired.cleanup();}
});
test('concept pages are fetched to completion and cache is partitioned by track then cleared on logout',async()=>{
 const item=(id,concept)=>({questionId:id,questionVersion:1,part:1,concept,core:'核心',apply:'套用',memory:'提示'});const app=await load({signed:true,cloudReviews:true,hash:'#concepts',conceptPages:{'':{items:[item('Q-A','概念甲')],cursor:'Q-A',hasMore:true},'Q-A':{items:[item('Q-B','概念乙')],cursor:'Q-B',hasMore:false}}});try{assert.match(app.h.concepts(),/概念甲/);assert.match(app.h.concepts(),/概念乙/);assert.ok(app.calls.some(call=>call.path.includes('after=Q-A')));const state=app.h.getState();state.settings.track='sqe';await app.h.loadReviewConcepts();assert.equal(app.h.getConceptCache().size,2);app.h.setAccount({...app.account,user:{...app.account.user,id:'10000000-0000-4000-8000-000000000002'}});assert.equal(app.h.getConceptCache().size,0);app.h.setGuest();assert.equal(app.h.getConceptCache().size,0);}finally{app.cleanup();}
});
test('reset does not claim complete session revocation when the provider could not revoke every device',async()=>{
 const app=await load({hash:'#reset',resetSessionsRevoked:false});try{await app.events.submit({target:{id:'auth-form',dataset:{mode:'reset'},data:{password:'test-password-123'},querySelector(){return {disabled:false,textContent:''};}},preventDefault(){}});assert.equal(location.hash,'#login');assert.match(app.main.innerHTML,/其他裝置的登入狀態尚未全部撤銷/);assert.match(app.main.innerHTML,/請重新登入後檢查帳戶安全/);}finally{app.cleanup();}
});

test('usage guide presents current five-step practice flow without promising AI or payments',async()=>{
 const app=await load({hash:'#help'});try{const html=app.main.innerHTML;assert.match(html,/開始你的備試練習/);assert.equal((html.match(/<li>/g)||[]).length,5);for(const text of ['選擇考試','選擇範圍','提交答案','閱讀固定詳解','重溫錯題','兩個不同的香港日期','訪客紀錄不會自動匯入','AI 問答及付款尚未開放'])assert.match(html,new RegExp(text));assert.doesNotMatch(html,/即時 AI 解答|立即付款/);}finally{app.cleanup();}
});
